---
- name: Clear the private destination access from host variables
  ansible.builtin.set_fact:
    campaign_private_destination_document: {}
    campaign_destination_environment: {}
    campaign_destination_azure_token: {}
    campaign_destination_azure_subscription: {}
  no_log: true
